# This file was generated by GoReleaser. DO NOT EDIT.
cask "portato" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "e0d52ce910b9465871d9de75169d3c12ceeb1eff888a4882a81cd9d1b473b34c"
      url "https://github.com/portuber/portato/releases/download/v#{version}/portato_#{version}_macOS_x86_64.tar.gz"
    end
    on_arm do
      sha256 "f53042b452943388e34902d2739c7bdb989fb5904308cac8a1aefb60e5d0e672"
      url "https://github.com/portuber/portato/releases/download/v#{version}/portato_#{version}_macOS_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "71bf86393455f9927eda6a2e71677b8507ab1c97428508ccbb503ae7857afcdc"
      url "https://github.com/portuber/portato/releases/download/v#{version}/portato_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "066c77fd0271cb2b9ac54bd841c469d3edfc3191ac1847961d504636f09abb87"
      url "https://github.com/portuber/portato/releases/download/v#{version}/portato_#{version}_linux_arm64.tar.gz"
    end
  end

  name "portato"
  desc "SSH port-forwarding manager with a TUI"
  homepage "https://github.com/portuber/portato"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "portato"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/portato"]
    end
  end

  # No zap stanza required

end
