# This file was generated by GoReleaser. DO NOT EDIT.
cask "portato" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "03a98a43e40b528b5ea429c7421f89a19dab3153b82c71612359703926e04d9c"
      url "https://github.com/portuber/portato/releases/download/v#{version}/portato_#{version}_macOS_x86_64.tar.gz"
    end
    on_arm do
      sha256 "e4a3403ccb297f3252a5f1a1ae8ccd450492d585a03c9f9afb80175bbdc19a06"
      url "https://github.com/portuber/portato/releases/download/v#{version}/portato_#{version}_macOS_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ef36b187755a3155b04299ea41e3062388e4bfb6d102badbea35d4d8246aca0d"
      url "https://github.com/portuber/portato/releases/download/v#{version}/portato_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "fe7e9ba889f1f64667056843d4f542a99c5c11138a1ad0c24777dd48f4839441"
      url "https://github.com/portuber/portato/releases/download/v#{version}/portato_#{version}_linux_arm64.tar.gz"
    end
  end

  name "portato"
  desc "SSH port-forwarding manager with a TUI"
  homepage "https://github.com/portuber/portato"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "portato"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/portato"]
    end
  end

  # No zap stanza required

end
