# This file was generated by GoReleaser. DO NOT EDIT.
cask "portato" do
  version "1.1.0"

  on_macos do
    on_intel do
      sha256 "33d298e2c5c70c7578a37300d537869601edb56d7520b3910cb2c47637c75b14"
      url "https://github.com/portuber/portato/releases/download/v#{version}/portato_#{version}_macOS_x86_64.tar.gz"
    end
    on_arm do
      sha256 "1fefe6869e60de24a40a195afcc3550693ac4df026500e2c34aaa2e5b7fd5a2a"
      url "https://github.com/portuber/portato/releases/download/v#{version}/portato_#{version}_macOS_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ccc2a0bfba22080a09839677ead5f8494306d5109b2166fc6309543582d4d137"
      url "https://github.com/portuber/portato/releases/download/v#{version}/portato_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "308e9a471455772735b8d0515fd79f92f9feb357d110664c24414c7d9397ccfe"
      url "https://github.com/portuber/portato/releases/download/v#{version}/portato_#{version}_linux_arm64.tar.gz"
    end
  end

  name "portato"
  desc "SSH port-forwarding manager with a TUI"
  homepage "https://github.com/portuber/portato"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "portato"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/portato"]
    end
  end

  # No zap stanza required

end
